[package]
org = "choreo"
name = "echo_service"
version = "3.1.1"

[[dependency]]
org = "ballerinax"
name = "aws.s3"
version = "3.4.0"

[dependencies]
"ballerinax/aws.s3" = "3.4.0"       # AWS S3 Connector maintained by WSO2
"ballerina/http" = "2.12.4"    # HTTP module for creating services
"ballerina/log" = "2.10.0"     # Logging module
"ballerina/runtime" = "1.5.0"  # Runtime module to fetch Ballerina version

[build-options]
observabilityIncluded = true
